# This is a basic workflow to help you get started with Actions

name: HCL AppScan on Cloud SAST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the AltoroJ-3.2 branch
  push:
    branches: [ AltoroJ-3.2 ]
  pull_request:
    branches: [ AltoroJ-3.2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Checkout ASoC SAST Repo
        uses: actions/checkout@v2
        with:
          repository: cwtravis/asoc-sast-linux
          path: asoc
          
      # Runs a set of commands using the runners shell
      - name: Gradle Build
        run: |
          ls -la
          cd main
          #gradle build
          
      # Runs AppScan Step
      - name: Perform HCL AppScan Security Analysis
        env:
          ASOC_KEY: ${{ secrets.ASOC_API_KEY }}
          ASOC_SECRET: ${{ secrets.ASOC_API_SECRET }}
          ASOC_SCAN_NAME: Automated Scan from Github Actions
          ASOC_APPID: ${{ secrets.ASOC_APPID }}
          ASOC_TARGET_DIR: main
          ASOC_WAIT: True
          
        run: |
          python3 asoc/RunSAST.py
        shell: bash
        
      - uses: actions/upload-artifact@v2
        with:
          name: hcl_appscan_results
          path: reports/
